import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import CopyButton from './components/CopyButton';
import { project, navLinks, pages, features } from './content';
import { Eyebrow, PageBody, PageMeta } from './site-pages';
import BlackHoleAnimation from './components/BlackHoleAnimation';

const command='pip install oblivion-agent';
function InstallCommand({value=command}:{value?:string}) { return <div className="r-install"><code>$ {value}</code><CopyButton text={value}/></div>; }
function Tag({children}:{children:ReactNode}) { return <span className="r-tag">{children}</span>; }
function Terminal({title,children}:{title:string;children:ReactNode}) { return <div className="r-terminal"><div className="r-terminal-bar"><i/><i/><i/><span>{title}</span></div><div className="r-terminal-body">{children}</div></div>; }

function Navbar() {
 const [menuOpen,setMenuOpen]=useState(false);
 const [activeDropdown,setActiveDropdown]=useState<'explore'|'persona'|null>(null);
 useEffect(()=>{
  if(!activeDropdown)return;
  const dismissOnOutsideClick=(event:PointerEvent)=>{
   if(event.target instanceof Element&&!event.target.closest('.persona'))setActiveDropdown(null);
  };
  const dismissOnEscape=(event:KeyboardEvent)=>{if(event.key==='Escape')setActiveDropdown(null)};
  document.addEventListener('pointerdown',dismissOnOutsideClick);
  document.addEventListener('keydown',dismissOnEscape);
  return ()=>{
   document.removeEventListener('pointerdown',dismissOnOutsideClick);
   document.removeEventListener('keydown',dismissOnEscape);
  };
 },[activeDropdown]);
 const toggleDropdown=(name:'explore'|'persona')=>setActiveDropdown(current=>current===name?null:name);
 const closeMenus=()=>{setActiveDropdown(null);setMenuOpen(false)};
 return <nav className="r-nav"><a className="r-brand" href="/" aria-label="Oblivion home">◫ OBLIVION</a><button type="button" className="r-menu-button" aria-label="Toggle navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}>☰</button><div className={`r-nav-links ${menuOpen?'is-open':''}`}>{navLinks.map(([label,href])=><a key={href} href={href} onClick={closeMenus}>{label}</a>)}<details className="persona persona-explore" open={activeDropdown==='explore'}><summary aria-expanded={activeDropdown==='explore'} onClick={event=>{event.preventDefault();toggleDropdown('explore')}}>Explore</summary><div>{pages.map(([label,href])=><a key={href} href={href} onClick={closeMenus}>{label}</a>)}</div></details><details className="persona" open={activeDropdown==='persona'}><summary aria-expanded={activeDropdown==='persona'} onClick={event=>{event.preventDefault();toggleDropdown('persona')}}>I Am...</summary><div><a href="/get-started" onClick={closeMenus}>A Developer</a><a href="/architecture" onClick={closeMenus}>Evaluating for a Team</a><a href={`${project.links.github}/blob/main/CONTRIBUTING.md`} onClick={closeMenus}>A Contributor</a><a href="/voice" onClick={closeMenus}>Curious About M.E.E.R.A.</a></div></details><a className="r-nav-cta" href="/get-started" onClick={closeMenus}>Get started <span>↗</span></a></div></nav>;
}

function Home() {
 return <><section className="r-intro-portal" aria-labelledby="oblivion-intro-title"><div className="r-intro-grid" aria-hidden="true"/><BlackHoleAnimation/><div className="r-intro-content"><span className="r-intro-overline"><i/> OPEN-SOURCE · AUTONOMOUS CODING <i/></span><h1 id="oblivion-intro-title" aria-label="OBLIVION AI"><span className="r-intro-name" aria-hidden="true">{'OBLIVION'.split('').map((letter,index)=><span key={`${letter}-${index}`}>{letter}</span>)}</span><span className="r-intro-ai" aria-hidden="true">AI</span></h1><p className="r-intro-kind">AN INTELLIGENCE FOR YOUR WORKSPACE</p><p>From first prompt to a reviewable patch.</p><a className="r-intro-cta" href="#home-content">Discover Oblivion <span>↓</span></a></div><div className="r-intro-coordinates" aria-hidden="true"><span>OBLIVION / 01</span><span>LOCAL · CLOUD · YOUR CHOICE</span></div><div className="r-intro-corner" aria-hidden="true">◉</div></section><section className="r-hero" id="home-content"><div className="r-container r-hero-grid"><div><Eyebrow>OPEN-SOURCE TERMINAL AGENT · {project.version}</Eyebrow><h1>Your terminal<br/>just got a brain.</h1><p>Oblivion is an autonomous AI coding agent with 38 tools, model choice, codebase-aware search, and an optional voice interface through M.E.E.R.A.</p><div className="r-actions"><InstallCommand/><a className="r-text-link" href={project.links.github} target="_blank" rel="noreferrer">View on GitHub ↗</a><a className="r-text-link" href={project.links.pypi} target="_blank" rel="noreferrer">PyPI ↗</a></div><div className="r-proof"><span>Python {project.python}</span><span>MIT License</span><span>ReAct agent</span><span>Voice optional</span></div></div><Terminal title="oblivion · project workspace"><p className="t-muted">workspace / api-service</p><p><b>you</b> &nbsp;Find why auth tests fail and fix the regression.</p><p><b className="t-violet">meera</b> &nbsp;I’ll trace the login flow, then run the focused tests.</p><p><span className="t-cyan">search_code</span> → auth/session.py · tests/test_auth.py</p><p><span className="t-amber">think</span> → compare session expiry with the expected behavior</p><p><span className="t-cyan">batch_edit</span> → prepare a focused, reviewable change</p><p className="t-green">✓ Diff ready · waiting for your approval</p><span className="r-cursor"/></Terminal></div></section>
 <div className="r-marquee" aria-label="Model providers"><div>{['Ollama Cloud','Ollama Local','Google Gemini','Groq','OpenRouter','Anthropic','OpenAI','DeepSeek','LiteLLM','Ollama Cloud','Ollama Local','Google Gemini','Groq','OpenRouter','Anthropic','OpenAI','DeepSeek','LiteLLM'].map((x,i)=><span key={`${x}-${i}`}><i/> {x}</span>)}</div></div>
 <section className="r-section r-paper"><div className="r-container r-demo-grid"><div><Eyebrow>ONE AGENT · MANY WAYS TO WORK</Eyebrow><h2>More than a chatbot.<br/>A collaborator in your CLI.</h2><p>Oblivion understands a request, chooses tools, observes what they return, and continues with that evidence in context. You stay close to the work and see where changes happen.</p><a className="r-text-link" href="/product">Get to know Oblivion <span>↗</span></a></div><div className="r-agent-console"><div className="r-console-label"><span>SESSION / 004</span><span className="r-live-dot">● ACTIVE</span></div><div><small>REQUEST</small><p>Explain this codebase and find the request handler.</p></div><div className="r-console-route"><span>search_code</span><b>→</b><span>find_symbol</span><b>→</b><span>read_file</span></div><div><small>OBSERVATION</small><p>3 relevant files · 1 route definition · caller map ready</p></div><div className="r-console-result"><span>RESULT</span><strong>Context before answer.</strong></div></div></div></section>
 <section className="r-section"><div className="r-container"><div className="r-section-top"><div><Eyebrow>OBLIVION / AT A GLANCE</Eyebrow><h2>Capability with a small footprint.</h2></div><a className="r-text-link" href="/product">Product overview ↗</a></div><div className="r-stats-inline">{[[`${project.tools}`,'documented tools'],[`${project.backends}`,'model backends in project docs'],[`${project.domains}`,'knowledge areas'],[project.version,'current package release']].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><p className="r-data-note">The README’s LOC, file count, and download figures are dated to the v3.1.0 snapshot; I’ve kept them off the current-version stats.</p></div></section>
 <section className="r-section r-paper"><div className="r-container"><div className="r-section-top"><div><Eyebrow>CAPABILITY MAP</Eyebrow><h2>One system, many useful paths.</h2><p className="r-intro-copy">Explore the parts of Oblivion by what you want to understand or do.</p></div><a className="r-text-link" href="/features">All capabilities ↗</a></div><div className="r-card-grid">{features.slice(0,6).map(f=><a className="r-feature" href={f.href} key={f.title}><small>{f.tag}</small><h3>{f.title}</h3><p>{f.text}</p><span>Explore ↗</span></a>)}</div></div></section>
 <section className="r-section"><div className="r-container r-split"><div><Eyebrow>THREE LAYERS OF CODE SEARCH</Eyebrow><h2>Find the right code,<br/>not just a keyword.</h2><p>Exact symbol lookup, FTS5 full-text search, and ChromaDB semantic results work together. AST-aware chunking keeps code structure attached to the indexed context.</p><a className="r-text-link" href="/architecture">See how search works ↗</a></div><div className="r-search-visual"><div><span>01</span><b>Symbol index</b><small>Exact function & class names</small></div><i>+</i><div><span>02</span><b>Full text · FTS5</b><small>Literal code and signature matches</small></div><i>+</i><div><span>03</span><b>Vector · ChromaDB</b><small>Semantic code relationships</small></div></div></div></section>
 <section className="r-section r-paper"><div className="r-container"><div className="r-section-top"><div><Eyebrow>KNOWLEDGE PACKS</Eyebrow><h2>Relevant context, automatically.</h2><p className="r-intro-copy">Fourteen domain areas, with advanced companion material where it helps. At most two packs load for one request.</p></div><a className="r-text-link" href="/knowledge-packs">Browse knowledge ↗</a></div><div className="r-pills">{['React','Next.js','Vue','TypeScript','Django','FastAPI','Docker','Security','Testing','Database','Debugging','Deployment'].map(x=><a href="/knowledge-packs" key={x}>{x}<span> ↗</span></a>)}</div></div></section>
 <section className="r-section"><div className="r-container r-split"><div><Eyebrow>MODEL RESILIENCE</Eyebrow><h2>Choose a model.<br/>Keep a fallback path.</h2><p>Use a local Ollama model, a free-tier hosted provider, or a LiteLLM-compatible model. The default runtime retries retryable failures through a configured chain.</p><a className="r-text-link" href="/models">Explore models and providers ↗</a></div><div className="r-fallback">{['Your selected model','Groq · GPT-OSS 120B','Google · Gemini 2.5 Flash','Ollama · Qwen 3.5 4B'].map((x,i)=><div key={x}><span className={i?'r-node':'r-node active'}>{String(i+1).padStart(2,'0')}</span><b>{x}</b><small>{i?'NEXT ROUTE':'FIRST TRY'}</small></div>)}</div></div></section>
 <section className="r-meera"><div className="r-container r-split"><div><Eyebrow>M.E.E.R.A. · VOICE OPTIONAL</Eyebrow><h2>Code by voice.<br/>Keep the same guardrails.</h2><p>Speak a task, let local Whisper transcribe it, and hear M.E.E.R.A. reply. The voice layer uses the same agent loop and tool permissions as text mode.</p><a className="r-text-link" href="/voice">Meet M.E.E.R.A. ↗</a></div><div className="r-wave-card"><div className="r-wave">{Array.from({length:35},(_,i)=><i key={i} style={{height:`${10+Math.abs(Math.sin(i*.65))*62}px`}}/>)}</div><div className="r-caption">FASTER-WHISPER <span>·</span> EDGE TTS / ELEVENLABS</div><p>Local speech input. A voice that answers back.</p><small>OPTIONAL EXTRA · 8 EDGE PERSONAS</small></div></div></section>
 <section className="r-section r-paper"><div className="r-container"><div className="r-section-top"><div><Eyebrow>START USING IT</Eyebrow><h2>Three commands to a working session.</h2></div><a className="r-text-link" href="/get-started">Full install guide ↗</a></div><div className="r-command-row"><span>01 · INSTALL</span><InstallCommand/><span>02 · CONFIGURE</span><InstallCommand value="oblivion init"/><span>03 · RUN</span><InstallCommand value="oblivion"/></div></div></section>
 <section className="r-quote"><div className="r-container"><Eyebrow>BUILT ON MODEST HARDWARE</Eyebrow><blockquote>13GB RAM.<br/>No GPU. Still useful.</blockquote><p>Developed and validated on a Lenovo V15 laptop.</p></div></section>
 <section className="r-closing"><div className="r-container r-closing-inner"><div><Eyebrow>OPEN SOURCE · MIT LICENSE</Eyebrow><h2>Give your terminal<br/>a brain.</h2><p>Install Oblivion, choose your model, and start with a project you know.</p><InstallCommand/><div className="r-actions"><a className="r-text-link" href={project.links.github} target="_blank" rel="noreferrer">GitHub ↗</a><a className="r-text-link" href={project.links.pypi} target="_blank" rel="noreferrer">PyPI ↗</a><a className="r-text-link" href="/get-started">Setup guide ↗</a></div></div><div className="r-big-mark">OBLIVION<span>v{project.version}</span></div></div></section></>;
}

function Footer() {
 const groups=[['Product',[['Overview','/product'],['Features','/features'],['How it works','/how-it-works'],['Use cases','/use-cases']]],['Reference',[['Tools','/tools'],['Models','/models'],['Knowledge packs','/knowledge-packs'],['Architecture','/architecture'],['Tech stack','/tech-stack']]],['Guides',[['Get started','/get-started'],['Configuration','/configuration'],['M.E.E.R.A. voice','/voice'],['MCP integrations','/integrations'],['Troubleshooting','/troubleshooting']]],['Project',[['Changelog','/changelog'],['Roadmap','/roadmap'],['Compare','/compare'],['FAQ','/faq'],['About','/about'],['Contributing','/contributing'],['Terms & conditions','/terms'],['Privacy policy','/privacy']]],['Community', [['GitHub',project.links.github],['PyPI',project.links.pypi],['Issues',project.links.issues],['Releases',project.links.releases],['Blog',project.links.blog],['LinkedIn',project.links.linkedin]]]];
 return <footer className="r-footer"><div className="r-footer-grid"><div className="r-footer-intro"><a className="r-brand" href="/">◫ OBLIVION</a><p>Open-source intelligence for the terminal.</p><Tag>MIT · v{project.version}</Tag></div>{groups.map(([name,links])=><div key={name as string}><h3>{name}</h3>{(links as string[][]).map(([label,href])=><a key={label} href={href} target={href.startsWith('http')?'_blank':undefined} rel={href.startsWith('http')?'noreferrer':undefined}>{label}</a>)}</div>)}</div><div className="r-footer-bottom"><span>© {new Date().getFullYear()} R. Rohith · MIT License</span><span>Built in Tamil Nadu, India</span></div></footer>;
}

export default function Redesign() {
 const path=window.location.pathname.replace(/\/$/,'')||'/';
 const meta=PageMeta({path});
 useEffect(()=>{
  document.title=path==='/'?'Oblivion Agent — Your terminal just got a brain':`${meta.title} · Oblivion Agent`;
  const desc=document.querySelector('meta[name=description]'); desc?.setAttribute('content',meta.description);
  document.querySelector('meta[property="og:description"]')?.setAttribute('content',meta.description);
  document.querySelector('meta[name="twitter:title"]')?.setAttribute('content',document.title);
  document.querySelector('meta[name="twitter:description"]')?.setAttribute('content',meta.description);
  const ogTitle=document.querySelector('meta[property="og:title"]'); ogTitle?.setAttribute('content',document.title);
  const sections=Array.from(document.querySelectorAll<HTMLElement>('.redesign main > section'));
  const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(reduced||!('IntersectionObserver' in window)){sections.forEach(s=>s.classList.add('motion-visible'));return;}
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('motion-visible');observer.unobserve(e.target);}}),{threshold:.12,rootMargin:'0px 0px -4% 0px'});
  sections.forEach(s=>{s.classList.add('motion-ready');observer.observe(s);}); return()=>observer.disconnect();
 },[path,meta.description,meta.title]);
 return <div className={`redesign ${path==='/'?'r-redesign-home':''} ${path==='/voice'?'is-meera':''}`}><Navbar/><main>{path==='/'?<Home/>:<PageBody path={path}/>}</main><Footer/></div>;
}
