import { useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import toolCatalog from './tool-registry.json';
import { advancedPacks, faqs, features, packs, project, providers, useCases, milestones } from './content';
import CopyButton from './components/CopyButton';

type ToolEntry = { name: string; group: string; tier: string; description: string };
const catalog = toolCatalog as ToolEntry[];
const github = project.links.github;

export function Eyebrow({ children }: { children: ReactNode }) { return <div className="eyebrow">// {children}</div>; }
export function PageIntro({ label, title, description }: { label: string; title: string; description: string }) {
  return <header className="r-page-intro"><Eyebrow>{label}</Eyebrow><h1>{title}</h1><p>{description}</p></header>;
}
function SectionHead({ label, title, text }: { label: string; title: string; text?: string }) {
  return <header className="section-heading"><Eyebrow>{label}</Eyebrow><h2>{title}</h2>{text && <p>{text}</p>}</header>;
}
function Terminal({ title, children }: { title: string; children: ReactNode }) {
  return <div className="r-terminal"><div className="r-terminal-bar"><i/><i/><i/><span>{title}</span></div><div className="r-terminal-body">{children}</div></div>;
}
function InstallCommand({ command = 'pip install oblivion-agent' }: { command?: string }) {
  return <div className="r-install"><code>$ {command}</code><CopyButton text={command}/></div>;
}
function PageSection({ children, paper = false, id }: { children: ReactNode; paper?: boolean; id?: string }) {
  return <section className={`r-section ${paper ? 'r-paper' : ''}`} id={id}><div className="r-container">{children}</div></section>;
}
function Cards({ items, className = '' }: { items: { title: string; text: string; tag?: string; href?: string }[]; className?: string }) {
  return <div className={`r-info-grid ${className}`}>{items.map((item) => <article className="r-info-card" key={item.title}>{item.tag && <small>{item.tag}</small>}<h3>{item.title}</h3><p>{item.text}</p>{item.href && <a href={item.href}>Explore <span>↗</span></a>}</article>)}</div>;
}
function Tag({ children }: { children: ReactNode }) { return <span className="r-tag">{children}</span>; }

export function ProductPage() {
  return <><PageIntro label="THE PRODUCT" title="An agent for the place you already work." description="Oblivion is an open-source coding agent that lives in your terminal. It understands a codebase, plans multi-step work, uses tools, and shows what it changed."/><PageSection><div className="r-split"><div><Eyebrow>NOT ANOTHER CHAT WINDOW</Eyebrow><h2>Oblivion is the shell.<br/>M.E.E.R.A. is the mind.</h2><p>Give it a task in natural language. Oblivion reasons through the next steps, searches your project, calls the tools it needs, and brings the result back to the terminal. Use text or speak when voice makes more sense.</p><a className="r-text-link" href="/how-it-works">Follow one task through the loop ↗</a></div><Terminal title="oblivion · your project"><p><span className="t-green">$</span> oblivion</p><p className="t-muted">Workspace indexed · ready</p><p><b>you</b> &nbsp;What handles authentication?</p><p><span className="t-cyan">search_code</span> &nbsp;Find auth implementation</p><p><span className="t-violet">find_symbol</span> &nbsp;Resolve relevant definitions</p><p className="t-green">M.E.E.R.A. &nbsp;Authentication starts in src/auth/...</p></Terminal></div></PageSection><PageSection paper><SectionHead label="DESIGNED AROUND REAL WORK" title="Useful without asking you to change your whole setup."/><Cards items={[{title:'Terminal-native',text:'A Textual interface keeps the conversation, tool activity, commands, and status close to your project.'},{title:'Open source · MIT',text:'Inspect the code, adapt it to your workflow, or contribute improvements.',href:github},{title:'Local or cloud models',text:'Choose a local Ollama model, a free-tier route, or a model provider you already use.',href:'/models'},{title:'Plays well with others',text:'Expose code intelligence to MCP clients instead of asking you to pick one assistant.',href:'/integrations'}]}/></PageSection><PageSection><SectionHead label="PROJECT AT A GLANCE" title="Small enough to inspect. Broad enough to help."/><div className="r-stats-inline">{[[`${project.tools}`,'user-facing tools'],[`${project.backends}`,'documented model backends'],[`${project.domains}`,'knowledge domains'],[project.version,'current package version']].map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><p className="r-data-note">Published package version from the project repository. Other scale figures in the README describe the earlier v3.1.0 snapshot.</p></PageSection></>;
}

export function FeaturesPage() {
  return <><PageIntro label="CAPABILITIES" title="A toolbox for thinking and doing." description="Each capability is a piece of the same terminal workflow: understand context, take a useful action, then inspect what happened."/><PageSection><Cards items={features.map(f=>({title:f.title,text:f.text,tag:f.tag,href:f.href}))}/></PageSection><PageSection paper id="simulator"><div className="r-split"><div><Eyebrow>AN UNEXPECTED EXTRA</Eyebrow><h2>Inside the TUI:<br/>an Intel 8085.</h2><p>The simulator includes a CPU core and assembler. It is a small working computer architecture lab tucked into an AI coding agent.</p><div className="r-actions"><Tag>8085 CPU</Tag><Tag>Assembler</Tag><Tag>Textual screen</Tag></div></div><Terminal title="8085 · simulator"><p className="t-muted">OBLIVION / SIMULATOR</p><p><span className="t-cyan">A</span>  3E 2A &nbsp; MVI A, 2AH</p><p><span className="t-cyan">B</span>  06 05 &nbsp; MVI B, 05H</p><p><span className="t-amber">PC</span> 0004 &nbsp;&nbsp; <span className="t-green">READY</span></p></Terminal></div></PageSection><PageSection><SectionHead label="THREE WAYS IN" title="Choose the interaction that fits the moment."/><Cards items={[{title:'Interactive TUI',text:'A persistent Textual session with history, workspace tools, and a command palette.'},{title:'One-shot tasks',text:'Give Oblivion a focused instruction from the command line and get a direct response.'},{title:'Voice mode',text:'Use M.E.E.R.A. with speech input and spoken output. Voice dependencies are optional.',href:'/voice'}]}/></PageSection></>;
}

export function HowItWorksPage() {
 const steps=[['01','You ask','Describe an outcome in natural language.'],['02','Think','The model turns the request into a next action or a final response.'],['03','Act','Oblivion selects a typed tool and applies its permission rules.'],['04','Observe','The tool result returns to the conversation as new context.'],['05','Repeat or respond','The loop continues until the task is complete or needs your input.']];
 return <><PageIntro label="THE REACT LOOP" title="Think. Act. Observe. Repeat." description="Oblivion uses a ReAct-style runtime: model reasoning and real tool results alternate until the task is done."/><PageSection><div className="r-loop-visual">{steps.map(([n,title,text],i)=><article key={n} className="r-loop-step"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div>{i<steps.length-1&&<b aria-hidden>↓</b>}</article>)}</div></PageSection><PageSection paper><div className="r-split"><div><Eyebrow>WHAT THE LOOP PROTECTS</Eyebrow><h2>Results come back<br/>before the next move.</h2><p>Tool output becomes the next observation. Oblivion can inspect the actual result instead of treating a model’s guess as proof. The runtime also has loop detection, exploration guards, conversation compression, and an iteration budget.</p><a className="r-text-link" href="/tools#safety">See the permission model ↗</a></div><Terminal title="agent · run"><p><span className="t-violet">THOUGHT</span> Locate the parser and its tests</p><p><span className="t-cyan">ACTION</span> search_code(query="parser tests")</p><p><span className="t-green">OBSERVATION</span> 4 relevant source chunks</p><p><span className="t-violet">THOUGHT</span> Read parser and run focused tests</p><p><span className="t-cyan">ACTION</span> read_file · run_tests</p><p className="t-green">FINAL_ANSWER · explain result and next step</p></Terminal></div></PageSection></>;
}

export function ToolsPage() {
 const [query,setQuery]=useState(''); const [tier,setTier]=useState('all'); const [group,setGroup]=useState('all');
 const tiers=['all','read','mutate','destructive']; const groups=['all',...Array.from(new Set(catalog.map(t=>t.group)))];
 const results=useMemo(()=>catalog.filter(t=>(tier==='all'||t.tier===tier)&&(group==='all'||t.group===group)&&`${t.name} ${t.description} ${t.group}`.toLowerCase().includes(query.toLowerCase())),[query,tier,group]);
 return <><PageIntro label="TOOL REGISTRY · 38 TOOLS" title="Real actions. Clear boundaries." description="Search the complete user-facing tool catalog. Each card shows what a tool does, where it fits, and its permission tier."/><PageSection id="safety"><div className="r-safety-banner"><div><Eyebrow>THE PERMISSION MODEL</Eyebrow><h2>Read. Mutate. Destructive.</h2><p>Read operations run without an approval prompt. Mutations normally show an approval step; session trust and auto mode can change that. High-risk shell patterns always require explicit approval.</p></div><div className="r-tier-legend"><Tag>READ · no prompt</Tag><Tag>MUTATE · approval / diff</Tag><Tag>DESTRUCTIVE · always ask</Tag></div></div></PageSection><PageSection paper><div className="r-tool-controls"><label className="r-search">Search tools<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try git_commit or semantic search"/></label><label>Permission tier<select value={tier} onChange={e=>setTier(e.target.value)}>{tiers.map(t=><option key={t} value={t}>{t==='all'?'All tiers':t}</option>)}</select></label><label>Category<select value={group} onChange={e=>setGroup(e.target.value)}>{groups.map(g=><option key={g} value={g}>{g==='all'?'All categories':g}</option>)}</select></label><span className="r-result-count">{results.length} / {catalog.length} tools</span></div><div className="r-tool-grid">{results.map(tool=><article className="r-tool-card" key={tool.name}><div className="r-card-top"><code>{tool.name}</code><Tag>{tool.tier}</Tag></div><p>{tool.description}</p><small>{tool.group.toUpperCase()}</small></article>)}</div>{results.length===0&&<p className="r-empty">No tools match this search.</p>}</PageSection><PageSection><SectionHead label="MUTATION FLOW" title="Preview the change before it touches disk." text="Mutating tool calls can be inspected and approved before execution. Destructive command patterns are never auto-approved."/><Terminal title="approval · diff preview"><p><span className="t-amber">TOOL</span> &nbsp;batch_edit</p><p><span className="t-muted">FILES</span> &nbsp;2 changes · atomic apply</p><p className="t-green">+ add parser guard for empty input</p><p className="t-red">- return parse(data)</p><p><span className="t-amber">APPROVAL</span> &nbsp;[Y] apply · [N] cancel</p></Terminal></PageSection></>;
}

export function ModelsPage() {
 return <><PageIntro label="MODEL ROUTING" title="Bring a model. Keep a route open." description="Project docs describe 13 model backends across local and hosted providers. Select a model directly, use free-tier choices, or connect a LiteLLM-compatible ID."/><PageSection paper><div className="r-provider-grid">{providers.map(p=><article className="r-provider-card" key={p.name}><span className="r-provider-mode">{p.mode}</span><h2>{p.name}</h2><p>{p.examples}</p><small>{p.note}</small></article>)}</div></PageSection><PageSection><div className="r-split"><div><Eyebrow>DEFAULT FALLBACK PATH</Eyebrow><h2>When one route fails,<br/>try the next.</h2><p>The source currently walks the selected model first, then Groq GPT-OSS 120B, Gemini 2.5 Flash, and local Ollama Qwen 3.5 4B. Retryable errors mark a model as temporarily exhausted; cooldown length depends on the error.</p><p className="r-data-note">Project documentation describes a broader 13-backend model set. The default runtime chain and the full set of selectable/custom models are different concepts.</p></div><div className="r-fallback">{['Your selected model','Groq · GPT-OSS 120B','Google · Gemini 2.5 Flash','Ollama · Qwen 3.5 4B'].map((v,i)=><div key={v}><span className={i?'r-node':'r-node active'}>{String(i+1).padStart(2,'0')}</span><b>{v}</b><small>{i?'FALLBACK':'FIRST TRY'}</small></div>)}</div></div></PageSection><PageSection paper><SectionHead label="LOCAL FIRST IS AN OPTION" title="Cloud is a choice, not a requirement." text="Use a local Ollama model for an offline-capable workflow. If you choose a hosted model, prompts and relevant tool output are sent to that provider."/><InstallCommand command="ollama run qwen3.5:4b"/></PageSection></>;
}

export function KnowledgePage() {
 return <><PageIntro label="KNOWLEDGE LIBRARY" title="A little context, when it matters." description="Workspace and request detection select relevant domain notes automatically. The injector caps each request at two packs to keep context focused."/><PageSection paper><div className="r-pack-grid">{packs.map((p,i)=><article key={p}><span>{String(i+1).padStart(2,'0')}</span><h2>{p}</h2><p>Detected from the project stack and the current request.</p><Tag>AUTO-DETECTED</Tag></article>)}</div><div className="r-advanced-packs"><h2>Advanced companion guides</h2><div>{advancedPacks.map(p=><Tag key={p}>{p}</Tag>)}</div><p>The repository contains advanced companions alongside the 14 named domain areas.</p></div></PageSection><PageSection><SectionHead label="HOW PACKS LOAD" title="Relevant notes, with a context cap."/><div className="r-pipeline">{[['01','Detect','Inspect files such as package.json and requirements.txt, plus the user’s request.'],['02','Select','Choose the knowledge notes that match the detected stack and task.'],['03','Inject','Load no more than two packs for one request.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></PageSection></>;
}

export function ArchitecturePage() {
 return <><PageIntro label="SYSTEM ARCHITECTURE" title="Context in. Evidence through. Changes out." description="Oblivion connects the terminal interface to a ReAct runtime, a hybrid code index, model routing, and a permission-aware tool layer."/><PageSection><div className="r-architecture-stack"><article><span>01 · INTERFACE</span><h2>Textual TUI</h2><p>Interactive conversation, tool activity, workspace status, commands, and sessions.</p></article><i>↓</i><article><span>02 · RUNTIME</span><h2>ReAct loop</h2><p>Prompts, model responses, tool dispatch, observations, and guarded iteration.</p></article><i>↓</i><article><span>03 · CONTEXT</span><h2>Search + memory</h2><p>SQLite symbol index and FTS5, ChromaDB vector search, AST-aware chunks, and project memory.</p></article><i>↓</i><article><span>04 · ACTION</span><h2>38 registered tools</h2><p>File operations, code intelligence, tests, git, web, packages, servers, and shell.</p></article><i>↓</i><article><span>05 · PROVIDERS</span><h2>LiteLLM + optional voice</h2><p>Model routing and M.E.E.R.A. audio input/output connect at the edge.</p></article></div></PageSection><PageSection paper><SectionHead label="HYBRID SEARCH" title="Three search layers. One ranked answer." text="Queries fan out across exact symbols, literal text, and semantic similarity; results are merged and deduplicated."/><div className="r-pipeline">{[['01','Symbol index','SQLite symbol lookup finds exact functions, classes, and variables.'],['02','Full text','SQLite FTS5 finds literal matches in code and signatures.'],['03','Vector search','ChromaDB + MiniLM finds conceptually related code.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="r-ranking">Exact line ranges are deduplicated <b>→</b> symbol matches rank first <b>→</b> vector results add conceptual context.</div></PageSection><PageSection id="memory"><div className="r-split"><div><Eyebrow>PROJECT MEMORY</Eyebrow><h2>Lessons that stay<br/>with the workspace.</h2><p>M.E.E.R.A. can save project conventions, architecture notes, gotchas, and preferences to a MEMORY.md file. A future session can recall them before it starts new work.</p><a className="r-text-link" href="/tools">See remember and recall tools ↗</a></div><Terminal title="workspace · MEMORY.md"><p><span className="t-violet">conventions</span> &nbsp;Use the existing API client</p><p><span className="t-cyan">architecture</span> &nbsp;Jobs are queued through Redis</p><p><span className="t-amber">gotchas</span> &nbsp;Run migrations before tests</p><p className="t-green">Saved in this workspace</p></Terminal></div></PageSection></>;
}

export function VoicePage() {
 const voices=['Aria','Jenny','Sonia','Natasha','Emma','Michelle','Guy','Ryan'];
 return <><PageIntro label="M.E.E.R.A. · VOICE" title="A coding agent you can talk to." description="M.E.E.R.A. means Multi-modal Engineering and Reasoning Assistant. Speech is optional; the same agent, tools, and safety gates remain underneath."/><PageSection paper><div className="r-split"><div><Eyebrow>VOICE PIPELINE</Eyebrow><h2>Speak. Transcribe.<br/>Think. Reply.</h2><p>faster-whisper transcribes audio locally. Oblivion passes the recognized text through its ReAct runtime, then M.E.E.R.A. speaks the response using Edge TTS or an optional ElevenLabs voice.</p><div className="r-pills"><Tag>16 kHz mono</Tag><Tag>Whisper STT</Tag><Tag>Edge TTS</Tag><Tag>ElevenLabs optional</Tag></div></div><div className="r-voice-pipeline">{[['01','Microphone','sounddevice input'],['02','Transcription','faster-whisper · local'],['03','Agent','same tools · same permissions'],['04','Speech','Edge TTS / ElevenLabs']].map(([n,t,d])=><div key={n}><span>{n}</span><b>{t}</b><small>{d}</small></div>)}</div></div></PageSection><PageSection><SectionHead label="VOICE PERSONALITY" title="Eight built-in Edge voices." text="Choose a speaking style in the terminal; ElevenLabs is available as an optional premium provider."/><div className="r-voice-grid">{voices.map((v,i)=><article key={v}><span>{String(i+1).padStart(2,'0')}</span><h3>{v}</h3><small>{['US · warm professional','US · conversational','UK · refined','AU · energetic','US · storyteller','US · mature','US · male','UK · male'][i]}</small></article>)}</div><p className="r-data-note">Wake-word listening (“Hey Meera”) uses the optional openWakeWord and microphone dependencies. Ctrl+T and the /voice command also start voice input.</p></PageSection><PageSection paper><div className="r-split"><div><Eyebrow>OPTIONAL INSTALL</Eyebrow><h2>Add voice only<br/>when you want it.</h2><p>Basic text mode has no microphone or Whisper dependency. The voice extra installs local speech input; the all extra also enables premium voice support.</p></div><div className="r-command-stack"><InstallCommand command={'pip install "oblivion-agent[voice]"'}/><InstallCommand command={'pip install "oblivion-agent[all]"'}/><Terminal title="oblivion · voice"><p><span className="t-green">$</span> oblivion</p><p className="t-muted">Press Ctrl+T or run /voice to begin speaking</p></Terminal></div></div></PageSection></>;
}

export function IntegrationsPage() {
 const tools=['read_file','list_dir','grep_files','file_exists','search_code','find_symbol','list_symbols','find_callers','project_map','recall'];
 return <><PageIntro label="MODEL CONTEXT PROTOCOL" title="Give your other tools Oblivion’s context." description="Run Oblivion as an MCP server so compatible clients can inspect a workspace through its code intelligence and filesystem tools."/><PageSection paper><div className="r-split"><div><Eyebrow>CONNECT A CLIENT</Eyebrow><h2>One command.<br/>A workspace-aware server.</h2><p>Start the stdio MCP server with <code>oblivion mcp</code>. Claude Desktop, Cursor, Zed, and other MCP clients can connect using their server configuration.</p><InstallCommand command="oblivion mcp"/></div><Terminal title="claude_desktop_config.json"><pre>{`{
  "mcpServers": {
    "oblivion": {
      "command": "oblivion",
      "args": ["mcp"],
      "env": {
        "WORKSPACE_DIR": "/path/to/project"
      }
    }
  }
}`}</pre></Terminal></div></PageSection><PageSection><SectionHead label="SERVER ACCESS MODES" title="Choose how much the client can do."/><Cards items={[{title:'Safe',text:'Expose the read-only set for workspace inspection and code understanding.'},{title:'Standard',text:'Allow safe tools plus the configured write/workspace actions.'},{title:'Full',text:'Include the complete server tool set; use only when that access is intended.'}]}/><p className="r-data-note">The MCP server has its own safe, standard, and full tool sets. These are separate from the interactive TUI’s per-call permission prompts.</p></PageSection><PageSection paper><SectionHead label="EXAMPLE READ TOOLS" title="A compact view into a workspace."/><div className="r-pills">{tools.map(t=><Tag key={t}>{t}</Tag>)}</div><p className="r-data-note">The checked repository defines additional server tools and access modes. The active client surface depends on the chosen mode and current server configuration.</p></PageSection></>;
}

export function UseCasesPage() {
 return <><PageIntro label="EXAMPLES" title="From a plain-language request to useful work." description="Oblivion is designed for tasks that need project context and more than one step. These examples show the kinds of requests it can work through."/><PageSection><div className="r-usecase-grid">{useCases.map((u,i)=><article key={u.name}><span>0{i+1} / TASK</span><h2>{u.name}</h2><blockquote>“{u.prompt}”</blockquote><p>{u.result}</p></article>)}</div></PageSection><PageSection paper><div className="r-split"><div><Eyebrow>START WITH YOUR PROJECT</Eyebrow><h2>Ask about your code,<br/>not a blank chat.</h2><p>Open Oblivion from a workspace, then ask it to explain, locate, change, test, or research something concrete.</p><a className="r-text-link" href="/get-started">Get started ↗</a></div><Terminal title="first prompts"><p>› what does this codebase do?</p><p>› where is the ReAct loop?</p><p>› find all callers of parse_response</p><p>› add error handling to the parser</p><p>› run tests for the files we changed</p></Terminal></div></PageSection></>;
}

export function SetupPage() {
 return <><PageIntro label="GET STARTED" title="Install. Set a model. Start talking to your code." description="The text agent installs from PyPI. Voice and premium speech are optional extras."/><PageSection><div className="r-setup-steps">{[['01','Install','pip install oblivion-agent','Install the package for the interactive terminal agent.'],['02','Run setup','oblivion','The first-run wizard helps choose a provider and write local configuration.'],['03','Open a project','cd your-project && oblivion','Launch Oblivion in the workspace you want it to understand.']].map(([n,t,c,d])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p><InstallCommand command={c}/></div></article>)}</div></PageSection><PageSection paper><div className="r-split"><div><Eyebrow>REQUIREMENTS</Eyebrow><h2>Python 3.11 or newer.</h2><p>The published package targets Python 3.11+ and supports Linux and macOS. The project recommends WSL2 on Windows; native Windows voice/audio may need additional setup.</p><div className="r-pills"><Tag>Python 3.11+</Tag><Tag>Linux</Tag><Tag>macOS</Tag><Tag>Windows · WSL2</Tag></div></div><Terminal title="install · optional extras"><p><span className="t-muted"># Core text agent</span></p><p>pip install oblivion-agent</p><p><span className="t-muted"># Local voice input</span></p><p>pip install "oblivion-agent[voice]"</p><p><span className="t-muted"># Voice + premium provider support</span></p><p>pip install "oblivion-agent[all]"</p></Terminal></div></PageSection><PageSection><SectionHead label="MODEL SETUP" title="Use the setup wizard or choose a model." text="Cloud models need their provider key. Local Ollama models need Ollama installed and the selected model available on your machine."/><Cards items={[{title:'Interactive setup',text:'Run oblivion and follow the first-run provider setup.'},{title:'Set a model directly',text:'Use the /model command in the TUI, or configure DEFAULT_MODEL.'},{title:'Local Ollama',text:'Install Ollama, pull a supported local model, then choose its LiteLLM-formatted model ID.'}]}/></PageSection></>;
}

export function ConfigurationPage() {
 const rows=[['DEFAULT_MODEL','Model ID in LiteLLM format','gemini/gemini-2.5-flash'],['GEMINI_API_KEY','Google provider key','your key'],['GROQ_API_KEY','Groq provider key','your key'],['OPENROUTER_API_KEY','OpenRouter provider key','your key'],['MAX_ITERATIONS','Agent loop ceiling','40'],['MAX_TOKENS','Response token limit','8192'],['TEMPERATURE','Sampling temperature','0.1'],['REQUIRE_APPROVAL_FOR_WRITE','Approval gate for writes','true'],['REQUIRE_APPROVAL_FOR_BASH','Approval gate for shell','true'],['WORKSPACE_DIR','Optional workspace override','/path/to/project'],['OBLIVION_HOME','Config home override','~/.oblivion'],['OBLIVION_CACHE','Cache directory override','~/.cache/oblivion']];
 return <><PageIntro label="CONFIGURATION" title="Tune the agent. Keep keys on your machine." description="Oblivion reads environment configuration from ~/.oblivion/config.env. Provider keys and runtime settings stay outside the project workspace."/><PageSection paper><div className="r-config-path"><span>CONFIG FILE</span><code>~/.oblivion/config.env</code><p>Environment variables override values from the config file; project defaults fill what remains unset.</p></div><div className="r-config-table"><div className="r-config-head"><span>KEY</span><span>WHAT IT CONTROLS</span><span>EXAMPLE</span></div>{rows.map(([key,desc,value])=><div className="r-config-row" key={key}><code>{key}</code><span>{desc}</span><code>{value}</code></div>)}</div></PageSection><PageSection><SectionHead label="A FEW EXAMPLES" title="Settings that change the feel of a session."/><Terminal title="~/.oblivion/config.env"><pre>{`DEFAULT_MODEL=gemini/gemini-2.5-flash
MAX_ITERATIONS=40
MAX_TOKENS=8192
TEMPERATURE=0.1
REQUIRE_APPROVAL_FOR_WRITE=true
REQUIRE_APPROVAL_FOR_BASH=true
FRIDAY_ENABLED=true
FRIDAY_VOICE=aria`}</pre></Terminal><p className="r-data-note">Never paste API keys into public repositories. Store provider credentials in the local config file or environment.</p></PageSection></>;
}

export function ComparePage() {
 const matrix=[['Open source · MIT','Yes','No','No','No'],['Terminal workflow','Native','IDE','IDE plugin','Native'],['Local model option','Ollama','No','No','No'],['Voice I/O','M.E.E.R.A.','Not listed','Not listed','Not listed'],['Multi-model fallback','13 backends','Not listed','Not listed','Single provider'],['MCP server','Built in','Not listed','Not listed','Not listed'],['Tool safety gates','Three tiers','Partial','Not listed','Approval controls']];
 return <><PageIntro label="WHERE IT FITS" title="A different shape of coding agent." description="Oblivion is an open-source terminal agent that can also hand code intelligence to other tools. This comparison summarizes the distinctions documented by the project."/><PageSection paper><div className="r-compare-wrap"><table className="r-compare-table"><thead><tr>{['Capability','Oblivion','Cursor','Copilot','Claude Code'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{matrix.map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></div><p className="r-data-note">Competitor cells are intentionally limited to comparisons published in the project README. Product features change; check each vendor’s current documentation for purchasing decisions.</p></PageSection><PageSection><div className="r-split"><div><Eyebrow>WHAT OBLIVION OPTIMIZES FOR</Eyebrow><h2>Open workflows.<br/>Visible decisions.</h2><p>Run your own model, inspect tool calls, decide when to approve changes, and reuse codebase search from another MCP client.</p><a className="r-text-link" href="/architecture">Explore the architecture ↗</a></div><Cards items={[{title:'Local-first option',text:'Ollama support gives you a route that can keep inference local.'},{title:'Not editor-bound',text:'The terminal interface and MCP server meet you where your tools already are.'}]}/></div></PageSection></>;
}

export function TechStackPage() {
 const layers=[['Core language','Python 3.11+','Agent runtime, tools, and package distribution.'],['Model gateway','LiteLLM','Provider routing and model-compatible identifiers.'],['Terminal UI','Textual + Rich','Interactive terminal screens and formatted output.'],['Hybrid search','SQLite FTS5 · ChromaDB · MiniLM','Exact symbol/text lookup with semantic retrieval.'],['Voice input','faster-whisper · sounddevice','Optional local transcription and microphone capture.'],['Voice output','Edge TTS · ElevenLabs','Speech synthesis with free Edge voices and optional premium provider.'],['Agent integration','MCP SDK','Serve tools, resources, and prompts to compatible clients.'],['Code indexing','Python AST · language-aware chunkers','Split source into functions, classes, and other useful code chunks.']];
 return <><PageIntro label="TECH STACK" title="Built from practical, inspectable pieces." description="The architecture combines a Python agent runtime with proven libraries for model routing, search, terminal UI, voice, and integrations."/><PageSection paper><div className="r-stack-list">{layers.map(([group,name,text])=><article key={group}><span>{group}</span><h2>{name}</h2><p>{text}</p></article>)}</div></PageSection><PageSection><SectionHead label="PROJECT SHAPE" title="A Python package with clear working parts."/><div className="r-pills">{['agent/ · runtime, LLM, memory, voice','tools/ · filesystem, git, web, tests','knowledge/ · detected domain packs','mcp_server/ · tools, resources, prompts','ui/ · Textual terminal screens','simulator/ · Intel 8085 CPU + assembler','db/ · session storage'].map(x=><Tag key={x}>{x}</Tag>)}</div><p className="r-data-note">Source layout reviewed from the linked repository at v3.4.3.</p></PageSection></>;
}

export function ChangelogPage() {
 return <><PageIntro label="PROJECT HISTORY" title="A terminal agent, one capability at a time." description="Milestones compiled from the project README and the source history. Published versions are marked separately from feature-era groupings."/><PageSection><div className="r-timeline">{milestones.map((m,i)=><article className={i%2?'right':''} key={m.version}><small>{m.version}</small><h2>{m.title}</h2><p>{m.text}</p></article>)}</div><p className="r-data-note">The current package metadata reports v3.4.3. See PyPI for exact published release dates and GitHub Releases for version-specific notes.</p><a className="r-text-link" href={project.links.releases} target="_blank" rel="noreferrer">Browse GitHub releases ↗</a></PageSection><PageSection paper><SectionHead label="CURRENT PACKAGE" title={`Oblivion Agent ${project.version}`} text={`Published ${project.released} · Python ${project.python} · MIT License.`}/><a className="r-text-link" href={project.links.pypi} target="_blank" rel="noreferrer">Open package on PyPI ↗</a></PageSection></>;
}

export function RoadmapPage() {
 const items=[['Voice personality','Explore interruption, proactive commentary, and emotion-aware tone.'],['More model routes','Continue extending the free-model fallback set.'],['A more modular TUI','Break the large terminal dashboard into smaller maintainable pieces.'],['Deeper MCP support','Expand editor integration and MCP tool coverage.']];
 return <><PageIntro label="DOCUMENTED ROADMAP" title="What Oblivion is exploring next." description="A roadmap is a direction, not a promise. These are the work areas listed by the project."/><PageSection paper><Cards items={items.map(([title,text])=>({title,text,tag:'EXPLORATION'}))}/></PageSection><PageSection><p className="r-data-note">Roadmap topics change as the project develops. Follow source discussions and releases for the latest status.</p><a className="r-text-link" href={project.links.github} target="_blank" rel="noreferrer">Follow the project on GitHub ↗</a></PageSection></>;
}

export function FAQPage() {
 return <><PageIntro label="FREQUENTLY ASKED QUESTIONS" title="Good questions before you install." description="Quick answers about privacy, model choices, safety, voice, Python, and integrations."/><PageSection paper><div className="r-faq-list">{faqs.map(([q,a],i)=><details key={q}><summary><span>{String(i+1).padStart(2,'0')}</span>{q}<b>+</b></summary><p>{a}</p></details>)}</div></PageSection><PageSection><SectionHead label="DIDN’T FIND IT?" title="Ask the people building it." text="Open a GitHub issue for setup help, bugs, or a feature discussion."/><a className="r-button" href={project.links.issues} target="_blank" rel="noreferrer">Open an issue ↗</a></PageSection></>;
}

export function AboutPage() {
 return <><PageIntro label="ABOUT THE PROJECT" title="Built because the terminal deserved more." description="Oblivion started with a simple idea: an agent should not stop at answering. It should be able to understand a codebase, take a considered action, and show its work."/><PageSection paper><div className="r-split"><div><Eyebrow>THE PERSON BEHIND IT</Eyebrow><h2>R. Rohith<br/>B.Sc. Computer Science</h2><p>Independent developer based in Tamil Nadu, India. Oblivion is an open-source project built around a terminal-native workflow, accessible model choices, voice, and a safety-conscious tool layer.</p><div className="r-actions"><a className="r-text-link" href={project.links.github} target="_blank" rel="noreferrer">GitHub ↗</a><a className="r-text-link" href={project.links.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a><a className="r-text-link" href="mailto:projectoblivion.dev@gmail.com">Email ↗</a></div></div><div className="r-creator-card"><div className="r-creator-mark">OR</div><p>“Code is conversation. Make it natural.”</p><small>— M.E.E.R.A.</small><div className="r-pills"><Tag>OPEN SOURCE</Tag><Tag>MIT LICENSE</Tag><Tag>MADE IN TAMIL NADU</Tag></div></div></div></PageSection><PageSection><SectionHead label="MAKE IT BETTER" title="There is room for your ideas."/><Cards items={[{title:'Report a bug',text:'Share the steps to reproduce, expected behavior, and what happened.',href:project.links.issues},{title:'Contribute code',text:'Fork the repository, create a feature branch, make a focused change, and open a pull request.',href:`${github}/blob/main/CONTRIBUTING.md`},{title:'Follow releases',text:'See the source and the exact changes behind each release.',href:project.links.releases}]}/></PageSection></>;
}

export function TroubleshootingPage() {
 const topics=[['Voice not working','Install the voice extra, confirm ffmpeg and microphone access, then inspect /voice status and /voice devices.'],['Provider returns 401','Check that the matching provider key exists in ~/.oblivion/config.env and restart the agent.'],['Provider is overloaded','The fallback chain skips retryable errors and can move to another configured model. You can also select one with /model.'],['Watcher cannot start','Linux systems can hit inotify watch limits. Check system watch settings and whether the workspace has large generated folders.'],['Windows audio setup','Use WSL2 as the project’s documented Windows path; audio input may need WSL passthrough configuration.'],['Need a fresh setup','Run oblivion init to launch the setup wizard again.']];
 return <><PageIntro label="TROUBLESHOOTING" title="Get unstuck without guessing." description="Start with the visible status and the relevant local configuration. These notes cover the common setup issues documented by the project."/><PageSection paper><Cards items={topics.map(([title,text])=>({title,text,tag:'QUICK FIX'}))}/></PageSection><PageSection><SectionHead label="USEFUL COMMANDS" title="Ask Oblivion what it sees."/><div className="r-pills">{['/model','/voice status','/voice devices','/wake status','/index status','/stats','/help'].map(x=><Tag key={x}>{x}</Tag>)}</div><p className="r-data-note">For provider failures, do not put API keys in screenshots or public issue reports.</p></PageSection></>;
}

export function ContributingPage() {
 return <><PageIntro label="CONTRIBUTING" title="Make the next session better." description="Oblivion is open source, and contributions are welcome. Keep changes focused, typed, documented, and easy to review."/><PageSection><div className="r-setup-steps">{[['01','Fork','Create a fork of the GitHub repository.'],['02','Branch','Create a feature branch for one focused change.'],['03','Build','Make the change and add/update the relevant documentation.'],['04','Verify','Run the project checks and try the changed flow manually.'],['05','Share','Commit clearly, push the branch, and open a pull request.']].map(([n,t,d])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></article>)}</div></PageSection><PageSection paper><div className="r-split"><div><Eyebrow>PROJECT CONVENTIONS</Eyebrow><h2>Focused patches.<br/>Useful context.</h2><p>Python 3.11+ features are welcome. Add type hints and public docstrings, and keep changes surgical—particularly within the large Textual UI module.</p></div><div className="r-actions"><a className="r-button" href={`${github}/blob/main/CONTRIBUTING.md`} target="_blank" rel="noreferrer">Contribution guide ↗</a><a className="r-text-link" href={project.links.issues} target="_blank" rel="noreferrer">Open issues ↗</a></div></div></PageSection></>;
}

const routeMap: Record<string, { component: () => ReactNode; title: string; label: string; description: string }> = {
 '/product': {component:ProductPage,title:'Product',label:'PRODUCT OVERVIEW',description:'Meet Oblivion, an open-source terminal agent for real software work.'},
 '/features': {component:FeaturesPage,title:'Features',label:'CAPABILITIES',description:'Explore Oblivion’s tools, voice, search, and terminal workflow.'},
 '/how-it-works': {component:HowItWorksPage,title:'How it works',label:'THE REACT LOOP',description:'Follow the reasoning and tool cycle behind Oblivion.'},
 '/tools': {component:ToolsPage,title:'Tools',label:'TOOL REGISTRY',description:'Browse all 38 user-facing Oblivion tools by category and safety tier.'},
 '/models': {component:ModelsPage,title:'Models',label:'MODEL ROUTING',description:'Explore Oblivion’s supported model providers and fallback chain.'},
 '/knowledge-packs': {component:KnowledgePage,title:'Knowledge packs',label:'KNOWLEDGE LIBRARY',description:'Explore auto-detected domain packs and advanced companions.'},
 '/architecture': {component:ArchitecturePage,title:'Architecture',label:'SYSTEM ARCHITECTURE',description:'Understand the ReAct runtime, hybrid search, memory, and tools.'},
 '/voice': {component:VoicePage,title:'M.E.E.R.A. voice',label:'VOICE ASSISTANT',description:'Meet M.E.E.R.A., Oblivion’s optional speech interface.'},
 '/integrations': {component:IntegrationsPage,title:'MCP integrations',label:'INTEGRATIONS',description:'Connect Oblivion to MCP-compatible clients.'},
 '/use-cases': {component:UseCasesPage,title:'Use cases',label:'EXAMPLES',description:'See examples of real terminal agent workflows.'},
 '/get-started': {component:SetupPage,title:'Get started',label:'QUICKSTART',description:'Install Oblivion Agent and launch it in your project.'},
 '/configuration': {component:ConfigurationPage,title:'Configuration',label:'CONFIGURATION',description:'Configure models, safety, voice, and workspace settings.'},
 '/roadmap': {component:RoadmapPage,title:'Roadmap',label:'ROADMAP',description:'Explore the directions Oblivion is considering next.'},
 '/compare': {component:ComparePage,title:'Compare',label:'COMPARISON',description:'Compare Oblivion’s shape with other coding tools.'},
 '/tech-stack': {component:TechStackPage,title:'Tech stack',label:'TECH STACK',description:'Libraries and technologies used by Oblivion Agent.'},
 '/changelog': {component:ChangelogPage,title:'Changelog',label:'PROJECT HISTORY',description:'Project milestones and published versions.'},
 '/faq': {component:FAQPage,title:'FAQ',label:'FAQ',description:'Answers about installation, privacy, models, and voice.'},
 '/about': {component:AboutPage,title:'About',label:'ABOUT',description:'The creator and motivation behind Oblivion Agent.'},
 '/troubleshooting': {component:TroubleshootingPage,title:'Troubleshooting',label:'TROUBLESHOOTING',description:'Find fixes for common Oblivion setup and provider issues.'},
 '/contributing': {component:ContributingPage,title:'Contributing',label:'CONTRIBUTING',description:'How to contribute to Oblivion Agent.'},
};

export function getPage(path: string) { return routeMap[path]; }
export function PageBody({ path }: { path: string }) { const page=routeMap[path]; if(!page)return <NotFoundPage/>; const Page=page.component; return <Page/>; }
export function PageMeta({ path }: { path: string }) { return routeMap[path] ?? {title:'Not found',label:'404',description:'That Oblivion page could not be found.'}; }
function NotFoundPage() { return <PageSection><PageIntro label="404 · ROUTE NOT FOUND" title="Nothing in this directory." description="That address does not match an Oblivion page."/><Terminal title="oblivion — zsh"><p><span className="t-green">$</span> cd /</p><p>Returned to the project home.</p></Terminal><a className="r-text-link" href="/">Back to home ↗</a></PageSection>; }
